name: Publish
on:
  push:
    branches:
      - master
      - next
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout repository'
        uses: actions/checkout@v2
      - name: 'Setup Node'
        uses: actions/setup-node@v2
      - name: 'Install depependencies'
        run: npm install
      - name: 'Build'
        run: npm run build
  release:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: 'Release'
      - run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
